Vagrant.configure("2") do |config|
config.vm.box = "CentOS7"

config.vm.network "private_network", ip: "192.168.33.10"

config.vm.provider "virtualbox" do |vb|
vb.customize ["modifyvm", :id, "--memory", "1024"]
end

config.vm.synced_folder ".", "/vagrant", mount_options:['dmode=777','fmode=777']
end
